name: Price Tracker

on:
  schedule:
    - cron: '3 */2 * * *'  # Runs every 2 hours at the top of the hour (3th minute)
  workflow_dispatch: # Allows manual triggering from the GitHub UI

jobs:
  track_prices:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install requests

      - name: Run price logger script
        run: python price_logger.py

      - name: Add changes to Git
        run: git add prices.txt

      - name: Commit and push changes
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: "Update asset prices"
          file_pattern: prices.txt
          github_token: ${{ secrets.GITHUB_TOKEN }}
