name: Price Logger (Multi-file)

on:
  schedule:
    - cron: '3 */2 * * *'  # Every 2 hours (UTC)
  workflow_dispatch:       # Allow manual trigger

jobs:
  log-prices:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.x

      - name: Install dependencies
        run: pip install requests

      - name: Run price logger
        run: python price_logger.py

      - name: Commit & Push new CSV
        run: |
          git config user.name "github-actions"
          git config user.email "github-actions@github.com"
          git add prices_*.csv
          git commit -m "📊 Add new price data file [CI run]" || echo "No changes to commit"
          git push https://x-access-token:${{ secrets.GITHUB_TOKEN }}@github.com/${{ github.repository }} HEAD:main
